//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibConsorcioOnline
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbConsorcioEntities : DbContext
    {
        public dbConsorcioEntities()
            : base("name=dbConsorcioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbAdmConsorcio> tbAdmConsorcio { get; set; }
        public DbSet<tbAnexoCarta> tbAnexoCarta { get; set; }
        public DbSet<tbCartaCredito> tbCartaCredito { get; set; }
        public DbSet<tbComprador> tbComprador { get; set; }
        public DbSet<tbFisicaJuridica> tbFisicaJuridica { get; set; }
        public DbSet<tbGrupoConsorcio> tbGrupoConsorcio { get; set; }
        public DbSet<tbPropostaCarta> tbPropostaCarta { get; set; }
        public DbSet<tbQualificacaoComprador> tbQualificacaoComprador { get; set; }
        public DbSet<tbQualificacaoVendedor> tbQualificacaoVendedor { get; set; }
        public DbSet<tbStatusCarta> tbStatusCarta { get; set; }
        public DbSet<tbStatusProposta> tbStatusProposta { get; set; }
        public DbSet<tbTipoConsorcio> tbTipoConsorcio { get; set; }
        public DbSet<tbUserPassword> tbUserPassword { get; set; }
        public DbSet<tbUsers> tbUsers { get; set; }
        public DbSet<tbVendedor> tbVendedor { get; set; }
    }
}
