//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibConsorcioOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCartaCredito
    {
        public tbCartaCredito()
        {
            this.tbPropostaCarta = new HashSet<tbPropostaCarta>();
            this.tbQualificacaoComprador = new HashSet<tbQualificacaoComprador>();
            this.tbQualificacaoVendedor = new HashSet<tbQualificacaoVendedor>();
        }
    
        public long cd_cartacredito { get; set; }
        public long cd_vendedor { get; set; }
        public int cd_admconsorcio { get; set; }
        public int cd_tipoconsorcio { get; set; }
        public int cd_statuscarta { get; set; }
        public string de_cidade { get; set; }
        public string de_uf { get; set; }
        public decimal nu_valorcredito { get; set; }
        public decimal nu_valorentrada { get; set; }
        public int nu_qtd_parcelas { get; set; }
        public decimal nu_valorparcela { get; set; }
        public decimal nu_saldocarta { get; set; }
        public string de_indexador { get; set; }
        public decimal nu_honorarios { get; set; }
        public decimal nu_taxajuros { get; set; }
    
        public virtual tbAdmConsorcio tbAdmConsorcio { get; set; }
        public virtual tbAnexoCarta tbAnexoCarta { get; set; }
        public virtual ICollection<tbPropostaCarta> tbPropostaCarta { get; set; }
        public virtual ICollection<tbQualificacaoComprador> tbQualificacaoComprador { get; set; }
        public virtual ICollection<tbQualificacaoVendedor> tbQualificacaoVendedor { get; set; }
        public virtual tbStatusCarta tbStatusCarta { get; set; }
        public virtual tbTipoConsorcio tbTipoConsorcio { get; set; }
        public virtual tbVendedor tbVendedor { get; set; }
    }
}
