//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibConsorcioOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbComprador
    {
        public tbComprador()
        {
            this.tbPropostaCarta = new HashSet<tbPropostaCarta>();
            this.tbQualificacaoComprador = new HashSet<tbQualificacaoComprador>();
            this.tbQualificacaoVendedor = new HashSet<tbQualificacaoVendedor>();
        }
    
        public long cd_comprador { get; set; }
        public string id_user { get; set; }
        public System.DateTime dt_create { get; set; }
        public long nu_qual_positiva { get; set; }
        public long nu_qual_negativa { get; set; }
        public bool bt_bloqueado { get; set; }
    
        public virtual ICollection<tbPropostaCarta> tbPropostaCarta { get; set; }
        public virtual ICollection<tbQualificacaoComprador> tbQualificacaoComprador { get; set; }
        public virtual ICollection<tbQualificacaoVendedor> tbQualificacaoVendedor { get; set; }
        public virtual tbUsers tbUsers { get; set; }
    }
}
