//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibConsorcioOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFisicaJuridica
    {
        public tbFisicaJuridica()
        {
            this.tbUsers = new HashSet<tbUsers>();
        }
    
        public int cd_fisjur { get; set; }
        public string de_fisjur { get; set; }
    
        public virtual ICollection<tbUsers> tbUsers { get; set; }
    }
}
