//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibConsorcioOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPropostaCarta
    {
        public long cd_propostacarta { get; set; }
        public long cd_cartacredito { get; set; }
        public long cd_vendedor { get; set; }
        public long cd_comprador { get; set; }
        public int cd_statusproposta { get; set; }
        public string de_mensagemproposta { get; set; }
    
        public virtual tbCartaCredito tbCartaCredito { get; set; }
        public virtual tbComprador tbComprador { get; set; }
        public virtual tbStatusProposta tbStatusProposta { get; set; }
        public virtual tbVendedor tbVendedor { get; set; }
    }
}
