//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibConsorcioOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStatusProposta
    {
        public tbStatusProposta()
        {
            this.tbPropostaCarta = new HashSet<tbPropostaCarta>();
        }
    
        public int cd_statusproposta { get; set; }
        public string de_statusproposta { get; set; }
    
        public virtual ICollection<tbPropostaCarta> tbPropostaCarta { get; set; }
    }
}
