//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibConsorcioOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsers
    {
        public tbUsers()
        {
            this.tbComprador = new HashSet<tbComprador>();
            this.tbVendedor = new HashSet<tbVendedor>();
        }
    
        public string id_user { get; set; }
        public string nm_user { get; set; }
        public string nm_apelido { get; set; }
        public int cd_fisjur { get; set; }
        public string cd_cpf { get; set; }
        public string cd_cnpj { get; set; }
        public string cd_ie { get; set; }
        public bool bit_bloqueio { get; set; }
    
        public virtual ICollection<tbComprador> tbComprador { get; set; }
        public virtual tbFisicaJuridica tbFisicaJuridica { get; set; }
        public virtual tbUserPassword tbUserPassword { get; set; }
        public virtual ICollection<tbVendedor> tbVendedor { get; set; }
    }
}
