//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibConsorcioOnline
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUserPassword
    {
        public string id_user { get; set; }
        public string de_password { get; set; }
        public System.DateTime dt_create { get; set; }
        public Nullable<System.DateTime> dt_update { get; set; }
        public bool bt_bloqueio { get; set; }
    
        public virtual tbUsers tbUsers { get; set; }
    }
}
